
[gen]

	[gen.arcane_crystal]
		#Generate Arcane Crystal Ore? [default: true]
		generate = true
		#Maximum size of Arcane Crystal Ore veins [default: 6]
		#Range: 0 ~ 100
		max_vein_size = 5
		#Maximum Arcane Crystal Ore veins per chunk [default: 3]
		#Range: 1 ~ 100
		count = 3
		#Maximum height for Arcane Crystal Ore to generate [default: 25]
		#Range: 1 ~ 256
		max_height = 25

	[gen.runestone]
		#Generate Runestone? [default: true]
		generate = true
		#Maximum size of Runestone veins [default: 3]
		#Range: 0 ~ 100
		max_vein_size = 3
		#Maximum Runestone veins per chunk [default: 2]
		#Range: 1 ~ 100
		count = 2
		#Maximum height for the Runestone to generate [default: 20]
		#Range: 1 ~ 256
		max_height = 20

	[gen.dark_runestone]
		#Generate Dark Runestone? [default: true]
		generate = true
		#Maximum size of Dark Runestone veins [default: 4]
		#Range: 0 ~ 100
		max_vein_size = 4
		#Maximum Dark Runestone veins per chunk [default: 2]
		#Range: 1 ~ 100
		count = 2
		#Maximum height for Dark Runestone to generate [default: 9]
		#Range: 1 ~ 256
		max_height = 9

	[gen.dark_stone]
		#Generate Dark Stone? [default: true]
		generate = true
		#Maximum size of Dark Stone veins [default: 20]
		#Range: 0 ~ 100
		max_vein_size = 20
		#Maximum Dark Stone veins per chunk [default: 20]
		#Range: 1 ~ 100
		count = 20
		#Maximum height for Dark Stone to generate [default: 8]
		#Range: 1 ~ 256
		max_height = 8

	[gen.xpetrified_ore]
		#Generate Xpetrified Ore? [default: true]
		generate = true

	[gen.stella_arcanum]
		#Generate Should Stella Arcanum? [default: true]
		generate = true
		#Maximum size of Stella Arcanum veins [default: 3]
		#Range: 0 ~ 100
		max_vein_size = 3
		#Maximum Stella Arcanum veins per chunk [default: 2]
		#Range: 1 ~ 100
		count = 2
		#Maximum height for Stella Arcanum to generate [default: 50]
		#Range: 1 ~ 256
		max_height = 50

	[gen.cherrywood_tree]
		#Generate Cherrywood Trees? [default: true]
		generate = true

	[gen.mysterywood_tree]
		#Generate Mysterywood Trees? [default: true]
		generate = true

	[gen.edelwood_tree]
		#Generate Edelwood Trees? [default: true]
		generate = true

	[gen.yellow_orchid]
		#Generate Yellow Orchid? [default: true]
		generate = true

